export const ADD_USER_REQUESTING = "ADD_USER_REQUESTING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const CANCEL_ADD_OR_EDIT_TIER = 'CANCEL_ADD_OR_EDIT_TIER'

export const ADD_COMMENT_CREATOR_REQUEST = "ADD_COMMENT_CREATOR_REQUEST"
export const ADD_COMMENT_CREATOR_SUCCESS = "ADD_COMMENT_CREATOR_SUCCESS"
export const ADD_COMMENT_CREATOR_ERROR = "ADD_COMMENT_CREATOR_ERROR"

export const GET_LIST_COMMENT_CREATOR_REQUEST = "GET_LIST_COMMENT_CREATOR_REQUEST"
export const GET_LIST_COMMENT_CREATOR_SUCCESS = "GET_LIST_COMMENT_CREATOR_SUCCESS"
export const GET_LIST_COMMENT_CREATOR_ERROR = "GET_LIST_COMMENT_CREATOR_ERROR"

export const HIDE_OR_UNHIDE_COMMENT_REQUEST = "HIDE_OR_UNHIDE_COMMENT_REQUEST"
export const HIDE_OR_UNHIDE_COMMENT_SUCCESS = "HIDE_OR_UNHIDE_COMMENT_SUCCESS"
export const HIDE_OR_UNHIDE_COMMENT_ERROR = "HIDE_OR_UNHIDE_COMMENT_ERROR"

export const GET_TRANSCRIPTION_REQUEST = "GET_TRANSCRIPTION_REQUEST"
export const GET_TRANSCRIPTION_SUCCESS = "GET_TRANSCRIPTION_SUCCESS"
export const GET_TRANSCRIPTION_ERROR = "GET_TRANSCRIPTION_ERROR"

export const UPDATE_TRANSCRIPT_REQUEST = "UPDATE_TRANSCRIPT_REQUEST"
export const UPDATE_TRANSCRIPT_SUCCESS = "UPDATE_TRANSCRIPT_SUCCESS"
export const UPDATE_TRANSCRIPT_ERROR = "UPDATE_TRANSCRIPT_ERROR"

export const PUBLISH_VIDEO_REQUEST = "PUBLISH_VIDEO_REQUEST"
export const PUBLISH_VIDEO_SUCCESS = "PUBLISH_VIDEO_SUCCESS"
export const PUBLISH_VIDEO_ERROR = "PUBLISH_VIDEO_ERROR"

export const UPDATE_TIER_FOR_VIDEO_REQUEST = "UPDATE_TIER_FOR_VIDEO_REQUEST"
export const UPDATE_TIER_FOR_VIDEO_SUCCESS = "UPDATE_TIER_FOR_VIDEO_SUCCESS"
export const UPDATE_TIER_FOR_VIDEO_ERROR = "UPDATE_TIER_FOR_VIDEO_ERROR"

export const GET_VIDEO_DETAILS_REQUEST = "GET_VIDEO_DETAILS_REQUEST"
export const GET_VIDEO_DETAILS_SUCCESS = "GET_VIDEO_DETAILS_SUCCESS"
export const GET_VIDEO_DETAILS_ERROR = "GET_VIDEO_DETAILS_ERROR"

export const GET_CREATOR_VIDEO_REQUEST = "GET_CREATOR_VIDEO_REQUEST"
export const GET_CREATOR_VIDEO_SUCCESS = "GET_CREATOR_VIDEO_SUCCESS"
export const GET_CREATOR_VIDEO_ERROR = "GET_CREATOR_VIDEO_ERROR"

export const GET_LIST_SUBSCRIBER_REQUEST = "GET_LIST_SUBSCRIBER_REQUEST"
export const GET_LIST_SUBSCRIBER_SUCCESS = "GET_LIST_SUBSCRIBER_SUCCESS"
export const GET_LIST_SUBSCRIBER_ERROR = "GET_LIST_SUBSCRIBER_ERROR"

export const GET_LIST_SUBSCRIBER_WITH_FILTER_REQUEST = "GET_LIST_SUBSCRIBER_WITH_FILTER_REQUEST"
export const GET_LIST_SUBSCRIBER_WITH_FILTER_SUCCESS = "GET_LIST_SUBSCRIBER_WITH_FILTER_SUCCESS"
export const GET_LIST_SUBSCRIBER_WITH_FILTER_ERROR = "GET_LIST_SUBSCRIBER_WITH_FILTER_ERROR"

export const SET_TIER_VIDEO_REQUEST = "SET_TIER_VIDEO_REQUEST"
export const SET_TIER_VIDEO_SUCCESS = "SET_TIER_VIDEO_SUCCESS"
export const SET_TIER_VIDEO_ERROR = "SET_TIER_VIDEO_ERROR"

export const TEST_REQUEST = "TEST_REQUEST"
export const TEST_SUCCESS = "TEST_SUCCESS"

export const GET_TIER_LIST_REQUEST = "GET_TIER_LIST_REQUEST"
export const GET_TIER_LIST_SUCCESS = "GET_TIER_LIST_SUCCESS"
export const GET_TIER_LIST_ERROR = "GET_TIER_LIST_ERROR"

export const ADD_TIER_REQUEST = "ADD_TIER_REQUEST"
export const ADD_TIER_SUCCESS = "ADD_TIER_SUCCESS"
export const ADD_TIER_ERROR = "ADD_TIER_ERROR"

export const EDIT_TIER_REQUEST = "EDIT_TIER_REQUEST"
export const EDIT_TIER_SUCCESS = "EDIT_TIER_SUCCESS"
export const EDIT_TIER_ERROR = "EDIT_TIER_ERROR"

export const SAVE_DRAFT_EMAIL_REQUEST = "SAVE_DRAFT_EMAIL_REQUEST"
export const SAVE_DRAFT_EMAIL_SUCCESS = "SAVE_DRAFT_EMAIL_SUCCESS"
export const SAVE_DRAFT_EMAIL_ERROR = "SAVE_DRAFT_EMAIL_ERROR"

export const VIDEO_PROCESS_REQUEST = "VIDEO_PROCESS_REQUEST"
export const VIDEO_PROCESS_SUCCESS = "VIDEO_PROCESS_SUCCESS"

export const EDIT_FREE_TIER_REQUEST = "EDIT_FREE_TIER_REQUEST"
export const EDIT_FREE_TIER_SUCCESS = "EDIT_FREE_TIER_SUCCESS"
export const EDIT_FREE_TIER_ERROR = "EDIT_FREE_TIER_ERROR"

export const DELETE_TIER_REQUEST = "DELETE_TIER_REQUEST"
export const DELETE_TIER_SUCCESS = "DELETE_TIER_SUCCESS"
export const DELETE_TIER_ERROR = "DELETE_TIER_ERROR"

export const CREATE_STYLES_SETTING_REQUEST = "CREATE_STYLES_SETTING_REQUEST"
export const CREATE_STYLES_SETTING_SUCCESS = "CREATE_STYLES_SETTING_SUCCESS"
export const CREATE_STYLES_SETTING_ERROR = "CREATE_STYLES_SETTING_ERROR"

export const EDIT_STYLES_SETTING_REQUEST = "EDIT_STYLES_SETTING_REQUEST"
export const EDIT_STYLES_SETTING_SUCCESS = "EDIT_STYLES_SETTING_SUCCESS"
export const EDIT_STYLES_SETTING_ERROR = "EDIT_STYLES_SETTING_ERROR"

export const GET_TOKEN = "GET_TOKEN"
export const SET_USER_ROLE = "SET_USER_ROLE"
export const CHANGE_MESSAGE = "CHANGE_MESSAGE"
export const CHANGE_CHANNEL_STATUS = "CHANGE_CHANNEL_STATUS"
export const GET_VIDEO_PROGRESS = "GET_VIDEO_PROGRESS"
export const CHECK_VIDEO_DURATION = "CHECK_VIDEO_DURATION"

export const EDIT_USER_PROFILE_REQUEST = "EDIT_USER_PROFILE_REQUEST"
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS"
export const EDIT_USER_PROFILE_ERROR = "EDIT_USER_PROFILE_ERROR"

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR"

export const CREATE_CHANNEL_REQUEST = "CREATE_CHANNEL_REQUEST"
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS"
export const CREATE_CHANNEL_ERROR = "CREATE_CHANNEL_ERROR"

export const EDIT_CHANNEL_REQUEST = "EDIT_CHANNEL_REQUEST"
export const EDIT_CHANNEL_SUCCESS = "EDIT_CHANNEL_SUCCESS"
export const EDIT_CHANNEL_ERROR = "EDIT_CHANNEL_ERROR"

export const SET_STRIPE_ACCOUNT_ID = "SET_STRIPE_ACCOUNT_ID"

export const SEND_EMAIL_NEW_VIDEO_REQUEST = "SEND_EMAIL_NEW_VIDEO_REQUEST"
export const SEND_EMAIL_NEW_VIDEO_SUCCESS = "SEND_EMAIL_NEW_VIDEO_SUCCESS"
export const SEND_EMAIL_NEW_VIDEO_ERROR = "SEND_EMAIL_NEW_VIDEO_ERROR"

export const GET_CHANNEL_REQUEST = "GET_CHANNEL_REQUEST"
export const GET_CHANNEL_SUCCESS = "GET_CHANNEL_SUCCESS"
export const GET_CHANNEL_ERROR = "GET_CHANNEL_ERROR"

export const GET_CHANNEL_STYLE_REQUEST = "GET_CHANNEL_STYLE_REQUEST"
export const GET_CHANNEL_STYLE_SUCCESS = "GET_CHANNEL_STYLE_SUCCESS"
export const GET_CHANNEL_STYLE_ERROR = "GET_CHANNEL_STYLE_ERROR"

export const EDIT_CHANNEL_STYLE_REQUEST = "GET_CHANNEL_STYLE_REQUEST"
export const EDIT_CHANNEL_STYLE_SUCCESS = "GET_CHANNEL_STYLE_SUCCESS"
export const EDIT_CHANNEL_STYLE_ERROR = "GET_CHANNEL_STYLE_ERROR"

export const CREATE_CHANNEL_STYLE_REQUEST = "GET_CHANNEL_STYLE_REQUEST"
export const CREATE_CHANNEL_STYLE_SUCCESS = "GET_CHANNEL_STYLE_SUCCESS"
export const CREATE_CHANNEL_STYLE_ERROR = "GET_CHANNEL_STYLE_ERROR"
